security:
  encoders:
    TodoBundle\Entity\User:
      algorithm: bcrypt

  providers:
    db_provider:
      entity:
        class: TodoBundle:User
        property: username

  firewalls:
    main:
      anonymous: ~
      provider: db_provider
      form_login:
        login_path: /login
        check_path: /login
      logout:
        path: /logout

  access_control:
    - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }